apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend-service
spec:
  ports:
    - name: http
      port: 5000
      targetPort: 80
      protocol: TCP
  selector:
    app: backend
  type: ClusterIP